# fly.toml app configuration file generated for compliment-bot-jdevmq on 2026-05-09T13:40:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'compliment-bot-jdevmq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
